version: "3"

services:
  app:
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/app"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
